baseURL = "http://example.org/"
languageCode = "en-us"
title = "giftakari | Software | Web Developer"
theme = "giftakari"
summaryLength = "10"
paginate = 10

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]
  page = ["HTML"]

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/headroom/headroom.js"
  [[params.plugins.js]]
  URL = "plugins/instafeed/instafeed.min.js"
  [[params.plugins.js]]
  URL = "plugins/masonry/masonry.js"
  [[params.plugins.js]]
  URL = "plugins/reading-time/readingTime.min.js"
  [[params.plugins.js]]
  URL = "plugins/smooth-scroll/smooth-scroll.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  

  
# navigation
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 3

[[menu.main]]
  name = "Projects"
  URL = "projects"
  weight = 4


[params]
logo = "images/logo.png"
home = "Home"
# hompage layout ( two layout is available,  you can set the another layout by change the value of homeLayoutToggle "true" to "false")
homeLayoutToggle = false
# Meta data
description = "Gift Akari is a passionate Software | Web Developer with vast experience in Business"
# about author
author = "giftakari"
authorImage = "images/banner-img.png"
shortDescription = "A passionate and goal-oriented Full-Stack Software | Web developer"
# Contact Form Action
contactFormAction = "#"
# Google Analitycs
googleAnalitycsID = "Your ID"
# copyright
copyright = " giftakari All rights reserve;"

  # Preloader
  [params.preloader]
  enable = true
  
  # search
  [params.search]
  enable = true

  # Instagram feed
  [params.instafeed]
  enable = true
  userID = "4044026246"
  accessToken = "4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"

  # footer
  [params.footer]

    #address
    [[params.footer.addresses]]
    address = "Sydney"
    
    [[params.footer.addresses]]
    address = " Australia"

    
    #contact information
    [[params.footer.contacts]]
    contactInfo = ""
    
    [[params.footer.contacts]]
    contactInfo = "Mail: exmaple@ymail.com"


  # social site
  [[params.social]]
  icon = "ti-facebook"
  URL = "#"
  
  [[params.social]]
  icon = "ti-twitter-alt"
  URL = "https://twitter.com/GODSGIFTAKARI"
  
  [[params.social]]
  icon = "ti-linkedin"
  URL = "https://www.linkedin.com/in/godsgift-akari-9951b05b/"
  
  [[params.social]]
  icon = "ti-github"
  URL = "https://github.com/giftakari"